# This is a basic workflow to help you get started with Actions

name: Neeto-Vue Release Action

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - TankNee-electron-11

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-windows:
    # The type of runner that the job will run on
    runs-on: windows-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out branch
        uses: actions/checkout@master

      - name: Install Node.js, NPM
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Build
        run: |
          npm install
          npm run build-publish
      - name: Compress Bundle
        run: |
          npm install -g bestzip
          cd dist/electron
          bestzip Neeto-Vue-win32-x64.zip Neeto-Vue-win32-x64/*
      - name: Upload Win Package
        uses: actions/upload-artifact@v1
        with:
          name: Windows_Dist
          path: dist/electron/Neeto-Vue-win32-x64.zip
  build-linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out branch
        uses: actions/checkout@master

      - name: Install Node.js, NPM
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Build
        run: |
          npm install
          npm run build-publish
      - name: Compress Bundle
        run: |
          npm install -g bestzip
          cd dist/electron
          bestzip Neeto-Vue-linux-x64.zip Neeto-Vue-linux-x64/*
      - name: Upload Linux Package
        uses: actions/upload-artifact@v1
        with:
          name: Linux_Dist
          path: dist/electron/Neeto-Vue-linux-x64.zip
  build-mac:
    # The type of runner that the job will run on
    runs-on: macos-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out branch
        uses: actions/checkout@master

      - name: Install Node.js, NPM
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Build
        run: |
          npm install
          npm run build-publish
      - name: Compress Bundle
        run: |
          npm install -g bestzip
          cd dist/electron
          bestzip Neeto-Vue-darwin-x64.zip Neeto-Vue-darwin-x64/*
      - name: Upload Mac Package
        uses: actions/upload-artifact@v1
        with:
          name: MacOS_Dist
          path: dist/electron/Neeto-Vue-darwin-x64.zip
  release:
    needs: [build-windows, build-linux, build-mac]
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v1
      - name: Download pre-built packages for Linux
        uses: actions/download-artifact@v1
        with:
          name: Linux_Dist
          path: artifacts
      - name: Download pre-built packages for Windows
        uses: actions/download-artifact@v1
        with:
          name: Windows_Dist
          path: artifacts
      - name: Download pre-built packages for MacOS
        uses: actions/download-artifact@v1
        with:
          name: MacOS_Dist
          path: artifacts
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: Neeto-Vue
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "artifacts/*"
          draft: true
          prerelease: true
